/* Maker expanded PDP blurbs — keyed by exact product title */
window.NORTHROOM_COPY = {
  "Abstract Art Print (Unframed)": { blurb: "An unframed abstract print in soft, cream-friendly tones. Ready for your own frame. Quiet art, not loud.", brand: "Unbranded" },
  "Acacia Drawer Organizers (Set of 3)": { blurb: "Three acacia drawer organizers for small things. Nested fit keeps a drawer sorted without plastic.", brand: "Unbranded" },
  "Acacia Serving Tray": { blurb: "A solid acacia tray with a raised rim. Useful for coffee, breakfast in bed, or clearing the coffee table. Wipe clean; oil the wood when it looks dry.", brand: "Unbranded" },
  "Acacia Wood Cutting Board": { blurb: "A solid acacia cutting board with a smooth face and natural grain. Good for prep or serving cheese. Oil lightly to keep it from drying out.", brand: "Unbranded" },
  "Arched Floor Mirror": { blurb: "An arched full-length floor mirror. Soft curve, lean or mount. Useful and calm in a bedroom or hall.", brand: "Unbranded" },
  "Bamboo Bath Caddy": { blurb: "A bamboo bath caddy that spans the tub. Room for a book, candle, or soap. Light and sturdy.", brand: "Unbranded" },
  "Bathroom Tumbler": { blurb: "A simple bathroom tumbler for rinsing. Compact cup for the sink.", brand: "Unbranded" },
  "Bouclé Lumbar Pillow Cover": { blurb: "A soft bouclé cover for a lumbar pillow. Adds quiet texture to a sofa or chair without looking busy. Removable for washing.", brand: "Unbranded" },
  "Brass Candle Snuffer": { blurb: "A small brass snuffer for taper candles. Puts the flame out cleanly. Compact drawer or mantel piece.", brand: "Unbranded" },
  "Brass Wall Sconce (Pair)": { blurb: "A pair of brass wall sconces with a warm metal finish. Simple mount for a hallway, bath, or beside a bed.", brand: "Unbranded" },
  "Canvas Storage Cubes (Set of 2)": { blurb: "Two canvas storage cubes with soft sides. Fit shelves or cubbies. Easy to lift and empty.", brand: "Unbranded" },
  "Ceramic Bud Vase (Set of 3)": { blurb: "Three small matte ceramic bud vases. One stem each. A quiet set for a windowsill or shelf.", brand: "Unbranded" },
  "Ceramic Butter Dish": { blurb: "A lidded ceramic butter dish. Keeps butter covered and soft on the table. Compact for daily use.", brand: "Unbranded" },
  "Ceramic Dinner Plates (Set of 4)": { blurb: "Four matte ceramic dinner plates. Everyday weight and a simple rim. Built for regular meals, not display only.", brand: "Unbranded" },
  "Ceramic Herb Planter": { blurb: "A compact ceramic herb planter for a porch or sill. Plain enough for kitchen herbs under cover.", brand: "Unbranded" },
  "Ceramic Incense Holder": { blurb: "A small ceramic incense holder with a simple ash catch. Compact for a desk or shelf.", brand: "Unbranded" },
  "Ceramic Jewelry Dish": { blurb: "A small ceramic jewelry dish for rings and earrings. Soft glaze, one quiet place on a dresser.", brand: "Unbranded" },
  "Ceramic Pendant Shade": { blurb: "A matte ceramic pendant shade. Clean downward light for a kitchen island or entry. Soft shape, no glare.", brand: "Unbranded" },
  "Ceramic Pitcher": { blurb: "A ceramic pitcher for water or drinks. Simple spout and a steady handle. Works on the table or counter.", brand: "Unbranded" },
  "Ceramic Planter (Medium)": { blurb: "A medium matte ceramic planter for an indoor plant. Simple shape, calm finish. Pair with a saucer if your plant needs drainage.", brand: "Unbranded" },
  "Ceramic Salt Cellar with Lid": { blurb: "A small lidded ceramic cellar for salt by the stove. Keeps a pinch close without a shaker. Countertop size.", brand: "Unbranded" },
  "Ceramic Taper Holders (Pair)": { blurb: "A pair of matte ceramic holders for standard taper candles. Steady base, plain profile. Good for a table or mantel.", brand: "Unbranded" },
  "Ceramic Tissue Box Cover": { blurb: "A ceramic tissue box cover with clean lines. Fits a standard box. Calm for the bath or nightstand.", brand: "Unbranded" },
  "Ceramic Utensil Crock": { blurb: "A matte ceramic crock for spoons and spatulas. Wide mouth, steady base. Keeps the counter tidy without looking styled.", brand: "Unbranded" },
  "Ceramic Wall Light Fixture": { blurb: "A ceramic wall light with a quiet shape. Soft wash of light for a hall, bath, or reading nook.", brand: "Unbranded" },
  "Closet Shelf Dividers (Set of 4)": { blurb: "Four closet shelf dividers that slide on. Keep stacks of sweaters or linens upright.", brand: "Unbranded" },
  "Cotton Hand Towels (Set of 4)": { blurb: "Four cotton hand towels for the bath or kitchen sink. Soft, quick to dry, easy to wash.", brand: "Unbranded" },
  "Dried Flower Bouquet": { blurb: "A dried flower bouquet for a vase. Soft color that lasts without water. Quiet on a shelf or table.", brand: "Unbranded" },
  "Faux Olive / Eucalyptus Stems": { blurb: "A few faux olive or eucalyptus stems for a vase. Soft green tones, no watering. Easy filler when you want greenery without upkeep.", brand: "Unbranded" },
  "Floating Wood Shelf": { blurb: "A floating wood shelf with a clean line. Wall mount for display or everyday objects.", brand: "Unbranded" },
  "Floor Lamp with Linen Shade": { blurb: "A simple floor lamp with a linen shade. Soft ambient light for a corner. Steady base, quiet presence.", brand: "Unbranded" },
  "Framed Abstract Print": { blurb: "A framed abstract print ready to hang. Soft shapes for a blank wall. Calm enough for a living room or bedroom.", brand: "Unbranded" },
  "Fringed Cotton Throw": { blurb: "A cotton throw with a simple fringe edge. Soft for the sofa. Everyday weight — not a heavy winter blanket.", brand: "Unbranded" },
  "Frosted Glass Night Light": { blurb: "A small frosted glass night light. Low, soft glow for a hall or bedside. Compact and calm.", brand: "Unbranded" },
  "Glass Oil / Vinegar Bottle": { blurb: "A clear glass bottle with a simple pour spout. For oil or vinegar on the counter. Easy to see the level and refill.", brand: "Unbranded" },
  "Glass Storage Jars (Set of 3)": { blurb: "Three clear lidded glass jars for the pantry. Easy to see what’s inside. Stackable basics.", brand: "Unbranded" },
  "Heavyweight Linen Pillowcases (Pair)": { blurb: "Two heavyweight linen pillowcases. Sturdy feel that softens over time. Pair with a quiet sheet set or duvet.", brand: "Unbranded" },
  "Large Stoneware Serving Bowl": { blurb: "A large stoneware bowl for salads or family serving. Steady and plain. One piece that earns its spot on the table.", brand: "Unbranded" },
  "Lidded Bamboo Box": { blurb: "A lidded bamboo box for small storage. Light, clean, shelf or dresser ready.", brand: "Unbranded" },
  "Linen Duvet Sham (Pair)": { blurb: "Two linen duvet shams to finish a quiet bed. Soft linen, easy to wash, matches a simple duvet setup.", brand: "Unbranded" },
  "Linen Laundry Hamper": { blurb: "A linen-look laundry hamper with soft sides. Freestanding and easy to empty. Quiet in a bedroom or bath.", brand: "Unbranded" },
  "Linen Napkin Set (Set of 4)": { blurb: "Four linen napkins with a soft hand and simple hem. Reusable for daily meals. Softens with use.", brand: "Unbranded" },
  "Linen Pillow Covers (Set of 2)": { blurb: "Two linen pillow covers for everyday sofa or bed pillows. Soft natural texture that softens with washing. Simple and calm — nothing loud.", brand: "Unbranded" },
  "Linen Tea Towels (Set of 3)": { blurb: "Three linen tea towels for daily kitchen use. Absorbent, sturdy, and plain. They hold up to washing without looking fussy.", brand: "Unbranded" },
  "Linen-Look Duvet Cover (Queen)": { blurb: "A queen duvet cover with a soft linen look. Light drape, easy to wash, calm for a quiet bedroom. Meant for everyday bedding, not a special occasion.", brand: "Unbranded" },
  "Linen-Look Shower Curtain": { blurb: "A linen-look shower curtain with a soft drape. Pattern-free. Standard fit for a quiet bath.", brand: "Unbranded" },
  "Marble Bookends (Pair)": { blurb: "A pair of marble bookends with solid weight. Soft stone for a shelf. Keeps books upright without looking decorative.", brand: "Unbranded" },
  "Match Jar with Striker": { blurb: "A small jar of matches with a striker lid. Handy beside candles on a shelf or mantel.", brand: "Unbranded" },
  "Matte Black Candle Warmer": { blurb: "Warms a jar candle from below so you get scent and a quiet glow without an open flame. Matte black finish fits a nightstand or shelf.", brand: "Unbranded" },
  "Matte Black Desk Lamp": { blurb: "A compact matte black lamp for a desk or shelf. Focused light in a small footprint. Simple and work-ready.", brand: "Unbranded" },
  "Matte Black Flatware Set (4)": { blurb: "A four-person matte black flatware set. Clean lines and everyday weight. Service for four without shine.", brand: "Unbranded" },
  "Matte Black Floor Lantern": { blurb: "A matte black floor lantern for a corner or hearth. Quiet glow at floor height. Plain enough to leave out.", brand: "Unbranded" },
  "Matte Black Pepper Mill": { blurb: "A matte black pepper mill with a simple grind. Quiet look for the counter or table. Adjust as you like.", brand: "Unbranded" },
  "Matte Black Robe Hooks (Set of 2)": { blurb: "Two matte black robe hooks for the wall. Simple mount for a robe or towel.", brand: "Unbranded" },
  "Matte Black Towel Bar": { blurb: "A matte black towel bar for the wall. Clean mount, everyday hold. Standard length.", brand: "Unbranded" },
  "Matte Ceramic Lamp with Linen Shade": { blurb: "A matte ceramic table lamp with a linen shade. Soft, even light for a bedside or side table. Quiet shape — no shine, no fuss.", brand: "Unbranded" },
  "Matte Ceramic Mugs (Set of 4)": { blurb: "Four matte ceramic mugs with a comfortable hold. Plain glaze for daily coffee or tea. Stackable enough for a small cabinet.", brand: "Unbranded" },
  "Matte Ceramic Soap Dispenser": { blurb: "A simple ceramic pump for the sink or bath. Matte finish, clean lines, easy to refill. Meant for daily hand soap or dish soap.", brand: "Unbranded" },
  "Matte Ceramic Toothbrush Holder": { blurb: "A compact matte ceramic toothbrush holder. Sink-side and plain.", brand: "Unbranded" },
  "Matte Ceramic Vase": { blurb: "A quiet ceramic vase for a few stems or branches. Matte finish, stable base, simple shape. Works with fresh or dried stems.", brand: "Unbranded" },
  "Matte Outdoor Lantern": { blurb: "A matte outdoor lantern for soft evening light on the patio. Quiet glow, outdoor-ready finish.", brand: "Unbranded" },
  "Matte Stoneware Bowls": { blurb: "Four everyday stoneware bowls with a matte glaze. Good weight for soup, cereal, or a small serving. Microwave and dishwasher friendly for real use.", brand: "Unbranded" },
  "Minimal Wall Clock": { blurb: "A minimal wall clock with a clear, quiet face. Easy to read. No clutter on the dial.", brand: "Unbranded" },
  "Natural Coir Welcome Mat": { blurb: "A natural coir welcome mat for the entry. Tough scrape, quiet look.", brand: "Unbranded" },
  "Natural Fiber Doormat": { blurb: "A natural fiber doormat with a tough weave. Scrapes dirt at the entry. Easy to shake clean.", brand: "Unbranded" },
  "Nested Mixing Bowls (Set of 3)": { blurb: "Three nested mixing bowls. Stack small in the cabinet; open up when you’re cooking. Everyday kitchen workhorses.", brand: "Unbranded" },
  "Nightstand Catchall Tray": { blurb: "A small catchall tray for the nightstand. Raised rim for keys, watch, or rings. Soft surface.", brand: "Unbranded" },
  "Northroom Ceramic Mug 11oz": { blurb: "An 11oz ceramic mug with the Northroom house mark. Everyday coffee or tea cup in a quiet white finish.", brand: "Northroom" },
  "Northroom Faux Suede Pillowcase": { blurb: "A faux suede pillowcase with the Northroom mark. Soft cover for a sofa or bed pillow. Insert not included.", brand: "Unbranded" },
  "Northroom Matte Poster 7x5": { blurb: "A small 7×5 matte poster of the Northroom mark. Quiet print for a shelf, frame, or desk.", brand: "Northroom" },
  "Outdoor Cushion Covers (Set of 2)": { blurb: "Two outdoor cushion covers in weather-ready fabric. Removable. Simple look for patio seating.", brand: "Unbranded" },
  "Outdoor Side Tray (Teak Look)": { blurb: "A teak-look outdoor side tray with a raised rim. For drinks and small plates by the chair.", brand: "Unbranded" },
  "Outdoor Throw Pillow Covers (Pair)": { blurb: "A pair of outdoor throw pillow covers. Fade-resistant fabric, easy zip. Removable for washing.", brand: "Unbranded" },
  "Oversized Bath Towels (Set of 2)": { blurb: "Two oversized cotton bath towels. Soft everyday weight for after a shower. Plain enough for a quiet bath.", brand: "Unbranded" },
  "Picture Ledge Shelf": { blurb: "A narrow picture ledge for frames or small objects. Easy to style and restyle. Wall mount.", brand: "Unbranded" },
  "Pillar Candles (Set of 3)": { blurb: "Three pillar candles in simple shapes. Clean burn for a table or hearth. Quiet light without scent claims.", brand: "Unbranded" },
  "Portable Rechargeable Table Lamp": { blurb: "A small rechargeable lamp you can move room to room. Soft glow without hunting for an outlet. Handy for a bedside, shelf, or patio table.", brand: "Unbranded" },
  "Quilted Cotton Coverlet": { blurb: "A quilted cotton coverlet for layering over sheets or under a duvet. Light warmth and clean lines. Machine washable for real use.", brand: "Unbranded" },
  "Rattan Magazine Holder": { blurb: "A rattan magazine holder with a soft natural weave. Freestanding by a chair or shelf.", brand: "Unbranded" },
  "Reed Diffuser Set": { blurb: "A reed diffuser set for soft scent without a flame. Low and steady on a shelf or bath counter.", brand: "Unbranded" },
  "Ribbed Glass Tumblers (Set of 2)": { blurb: "Two clear ribbed glass tumblers. Simple enough for everyday water or drinks. Light texture in the glass, nothing fancy.", brand: "Unbranded" },
  "Round Wall Mirror": { blurb: "A round wall mirror with a simple frame. Clean reflection for an entry or wall. Quiet shape.", brand: "Unbranded" },
  "Seagrass Storage Baskets (Set of 2)": { blurb: "Two seagrass baskets for blankets or clutter. Natural weave, nested sizes. Soft storage that stays visible.", brand: "Unbranded" },
  "Sheer Linen Curtain Panels (Pair)": { blurb: "A pair of sheer linen panels. Softens daylight without blocking the room. Quiet privacy for a living room or bedroom.", brand: "Unbranded" },
  "Soft Cotton Sheet Set (Queen)": { blurb: "A full queen sheet set in soft cotton. Breathable for nightly use. Plain finish — no pattern noise.", brand: "Unbranded" },
  "Soft Knit Throw Blanket": { blurb: "A soft knit throw for the couch or bed. Mid-weight warmth, easy to fold, plain enough for any quiet room.", brand: "Unbranded" },
  "Stone Coasters (Set of 4)": { blurb: "Four natural stone coasters. Absorbent and quiet on the table. Simple enough to leave out.", brand: "Unbranded" },
  "Stoneware Dinner Bowls (Set of 4)": { blurb: "Four stoneware dinner bowls for soup, grain, or salad. Everyday weight, plain finish.", brand: "Unbranded" },
  "Stonewashed Linen Euro Shams (Pair)": { blurb: "A pair of stonewashed linen euro shams. Soft, lived-in look for the bed. Calm texture without pattern.", brand: "Unbranded" },
  "Taper Candles (Box of 6)": { blurb: "A box of six standard taper candles. Slim profile, even burn. Pair with the ceramic holders.", brand: "Unbranded" },
  "Textured Bath Mat": { blurb: "A textured bath mat with a soft step. Simple look underfoot. Machine washable for real use.", brand: "Unbranded" },
  "Travertine Tray": { blurb: "A travertine tray with a raised edge. Natural stone for the coffee table, bath, or nightstand. Catchall for small things.", brand: "Unbranded" },
  "Under-Sink Bin (Pair)": { blurb: "A pair of compact under-sink bins. Easy pull for cleaning supplies or extras. Fits tight spaces.", brand: "Unbranded" },
  "Waffle Cotton Throw": { blurb: "A light cotton throw with a soft waffle weave. Works on the couch or folded at the end of the bed. Breathable enough for year-round use.", brand: "Unbranded" },
  "Wall Hook Rack (Wood + Brass)": { blurb: "A wood and brass wall hook rack. Multi-hook for an entry or bath. Warm metal, simple wood.", brand: "Unbranded" },
  "Wall-Mounted Soap Dish": { blurb: "A wall-mounted soap dish that keeps the bar dry and off the sink. Compact and useful.", brand: "Unbranded" },
  "Washcloths (Set of 6)": { blurb: "Six soft cotton washcloths. Plain and washable. Always useful in a bath drawer.", brand: "Unbranded" },
  "Washed Linen Table Runner": { blurb: "A washed linen runner with a soft drape. Sits quietly down the table for everyday meals or a simple dinner. Easy to wash and put back.", brand: "Unbranded" },
  "Weathered Wood Plant Stand": { blurb: "A weathered wood plant stand that raises a pot off the ground. Outdoor-ready height and finish.", brand: "Unbranded" },
  "Wood Base Table Lamp": { blurb: "A wood-base table lamp with a simple shade. Warm and plain for a bedside or side table. Soft light without looking styled.", brand: "Unbranded" },
  "Wood Salad Servers (Pair)": { blurb: "A pair of smooth wood salad servers. Light in the hand, simple for tossing and serving.", brand: "Unbranded" },
  "Woven Placemats (Set of 4)": { blurb: "Four woven placemats for everyday place settings. Flat weave, easy to wipe, simple enough to leave out.", brand: "Unbranded" },
  "Woven Wall Hanging": { blurb: "A woven wall hanging in soft neutrals. Quiet texture for a blank wall. Soft, not loud.", brand: "Unbranded" }
};
